### PR TITLE
retry getFileInfo on error

### LINKED ISSUE #64: Creating storage token retry disables duplicate file name check and overwrites old file
### Package Versions

Replace the values below using the output from `npm list storj`. Use ```npm list -g storj``` if installed globally.

```
Storjcli: 2.0.0 | Core: 5.0.1
```

Replace the values below using the output from `node --version`.

```
v4.6.9
```

### Expected Behavior

Please describe the program's expected behavior. Include an example of your
usage code in the back ticks below if applicable.

```
 [Wed Nov 16 2016 01:54:08 GMT+0100 (CET)] [info]   1 file(s) to upload.
 [Wed Nov 16 2016 01:54:09 GMT+0100 (CET)] [info]   Generating encryption key...
 [Wed Nov 16 2016 01:54:09 GMT+0100 (CET)] [warn]   [ file ] Already exists in bucket. Uploading to (2016-11-16T00;54;09.966Z)-file
```

### Actual Behavior

Please describe the program's actual behavior. Please include any stack traces
or log output in the back ticks below.

storj-cli is overwriting my old file. This is only happening if "Creating storage token" needs a few retries.
```
 [Wed Nov 16 2016 02:04:18 GMT+0100 (CET)] [info]   1 file(s) to upload.
 [Wed Nov 16 2016 02:04:19 GMT+0100 (CET)] [info]   Generating encryption key...
 [Wed Nov 16 2016 02:04:30 GMT+0100 (CET)] [info]   Encrypting file "/root/.storjcli/upload"
 [Wed Nov 16 2016 02:04:30 GMT+0100 (CET)] [info]   [ file ] Encryption complete
 [Wed Nov 16 2016 02:04:30 GMT+0100 (CET)] [info]   [ file ] Creating storage token... (retry: 0)
 [Wed Nov 16 2016 02:04:41 GMT+0100 (CET)] [info]   [ file ] Creating storage token... (retry: 1)
 [Wed Nov 16 2016 02:04:51 GMT+0100 (CET)] [info]   [ file ] Creating storage token... (retry: 2)
 [Wed Nov 16 2016 02:04:52 GMT+0100 (CET)] [info]   [ file ] Storing file, hang tight!
```

### Steps to Reproduce

Please include the steps the reproduce the issue, numbered below. Include as
much detail as possible.

1. Upload the same file multiple times.
2. Check the logfile.

### PR DESCRIPTION
**Pull request by littleskunk**
* Closes #64

### CODE REVIEW

**Comment by littleskunk** [comment]
Oh fuck. The fix will only work for non empty buckets. An empty bucket will cause this:
```
 [Sat Nov 19 2016 13:59:02 GMT+0100 (CET)] [info]   1 file(s) to upload.
 [Sat Nov 19 2016 13:59:04 GMT+0100 (CET)] [info]   Generating encryption key...
 [Sat Nov 19 2016 13:59:04 GMT+0100 (CET)] [info]   [ file ] Getting file info... (retry: 0)
 [Sat Nov 19 2016 13:59:05 GMT+0100 (CET)] [info]   [ file ] Getting file info... (retry: 1)
 [Sat Nov 19 2016 13:59:06 GMT+0100 (CET)] [info]   [ file ] Getting file info... (retry: 2)
 [Sat Nov 19 2016 13:59:06 GMT+0100 (CET)] [info]   [ file ] Getting file info... (retry: 3)
 [Sat Nov 19 2016 13:59:07 GMT+0100 (CET)] [info]   [ file ] Getting file info... (retry: 4)
 [Sat Nov 19 2016 13:59:07 GMT+0100 (CET)] [info]   [ file ] Getting file info... (retry: 5)
 [Sat Nov 19 2016 13:59:08 GMT+0100 (CET)] [info]   [ file ] Getting file info... (retry: 6)
```

I will have to work on it later.

**Comment by littleskunk** [comment]
Fixed
```
 [Sat Nov 19 2016 21:03:04 GMT+0100 (CET)] [info]   1 file(s) to upload.
 [Sat Nov 19 2016 21:03:05 GMT+0100 (CET)] [info]   Generating encryption key...
 [Sat Nov 19 2016 21:03:05 GMT+0100 (CET)] [info]   [ file ] Getting file info... (retry: 0)
 [Sat Nov 19 2016 21:03:06 GMT+0100 (CET)] [info]   Encrypting file "/root/.storjcli/file"
 [Sat Nov 19 2016 21:03:08 GMT+0100 (CET)] [info]   [ file ] Encryption complete
```

**Comment by bookchin** [comment]
This needs to be rebased

**Comment by littleskunk** [comment]
rebased and ready to merge

**Comment by braydonf** [comment]
There are retries on all requests via https://github.com/Storj/core/blob/master/lib/bridge-client/index.js#L1124 if the error is of a retry nature, is this still needed?

**Comment by littleskunk** [comment]
Good question. I can try it this weekend. My testnode is offline for a hardware upgrade.

**Comment by littleskunk** [comment]
I can't reproduce it. Looks like it is fixed already.

**Pull request closed without merging**
